# This is a basic workflow to help you get started with Actions

name: Liquibase

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    steps:
      - name: Google Cloud SQL Proxy
        uses: mattes/gce-cloudsql-proxy-action@v1.0.1
        with:
          creds: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          instance: clearchoice-main-nprod:us-west1:datawarehouse

      # Checks-out repository under $GITHUB_WORKSPACE, so job can access it
      - name: check out repo
        uses: actions/checkout@v2
      
      - name: debug
        run: | 
          psql -V
          psql -d postgres -h 127.0.0.1 -p 5432 -U postgres -l

#      - name: run liquibase
#        uses: liquibase/liquibase-github-action@v2
#        with:
#          operation: 'status'
#          classpath: '/'
#          changeLogFile: 'changelog_master.json'
#          username: postgres
#          password: P@ssw0rd
#          url: jdbc:postgresql:postgres
