# This is a basic workflow to help you get started with Actions

name: Liquibase

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-database:
    runs-on: ubuntu-latest
    name: Deploy database
    steps:
      - name: Google Cloud SQL Proxy
        uses: mattes/gce-cloudsql-proxy-action@v1.0.1
        with:
          creds: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          instance: clearchoice-main-nprod:us-west1:datawarehouse

      # Checks-out repository under $GITHUB_WORKSPACE, so job can access it
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: install liquibase
        run : |
          wget -nv https://github.com/liquibase/liquibase/releases/download/v4.9.0/liquibase-4.9.0.tar.gz
          tar -xf liquibase-4.9.0.tar.gz
          
      - name: debug
        run: | 
          ls -l
          find salesforce
#          export PGPASSWORD="P@ssw0rd"
#          psql -d postgres -h 127.0.0.1 -p 5432 -U postgres -d datawarehouse -c '\dt'

      - name: Run liquibase
        run: |
          ./liquibase update
